<?php

namespace Database\Seeders;

use App\Models\ZRC;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ZRCSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        ZRC::create(['RCID' => 'RC','RCRTCD' => '1','RCDESC' => 'Dummy','RCEDTE' => '20171231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '0','RCNRTE' => '0','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RZ','RCRTCD' => 'TAX1','RCDESC' => 'TAX1','RCEDTE' => '20130101','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '0','RCNRTE' => '0','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '16','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IVA','RCDESC' => 'IVATRASLADADO16%MMVO','RCEDTE' => '20130101','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '16','RCNRTE' => '16','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IVA0','RCDESC' => 'Ivatasa0','RCEDTE' => '20191231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '0','RCNRTE' => '0','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'EX','RCDESC' => 'IvaExento','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '0','RCNRTE' => '0','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IRT10','RCDESC' => 'RetencionIVA','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-10.6667','RCNRTE' => '-10.6667','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IVA16','RCDESC' => 'ImpuestoalValorAgregado','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '16','RCNRTE' => '16','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'RRT10','RCDESC' => 'RetenciondeHonorarios','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-10','RCNRTE' => '-10','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IRF04','RCDESC' => 'RetencionFletes','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-4','RCNRTE' => '-4','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IRF02','RCDESC' => 'ISH2.00','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '2','RCNRTE' => '2','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'RET10','RCDESC' => 'RetenciondeSoporteTecnico','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-10','RCNRTE' => '-10','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RZ','RCRTCD' => 'RETST','RCDESC' => 'RetenciondeSoporteTecnico','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-25','RCNRTE' => '-25','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'RET25','RCDESC' => 'RetenciondeSoporteTecnico','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-25','RCNRTE' => '-25','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'RRT16','RCDESC' => 'RetencionSCRAP','RCEDTE' => '20201231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-16','RCNRTE' => '-16','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IVA04','RCDESC' => 'ImpalValorAgregFletes.25','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '4','RCNRTE' => '4','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IRT01','RCDESC' => 'ImpCedular1%','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-1','RCNRTE' => '-1','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IRT02','RCDESC' => 'ImpCedular2%','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-2','RCNRTE' => '-2','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'RET15','RCDESC' => 'RetenciondeGarantias','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-15','RCNRTE' => '-15','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IRT06','RCDESC' => 'RETENCIONOUTSORCING6%','RCEDTE' => '20200101','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-6','RCNRTE' => '-6','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IRT05','RCDESC' => 'ImpCedular5%','RCEDTE' => '20200101','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-5','RCNRTE' => '-5','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IRT25','RCDESC' => 'ImpCedular2.5%','RCEDTE' => '20200101','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-2.5','RCNRTE' => '-2.5','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IVA08','RCDESC' => 'IVAAcreditable8%Frontera','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '8','RCNRTE' => '8','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IRF4','RCDESC' => 'ISH4.00','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '4','RCNRTE' => '4','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'RET01','RCDESC' => 'ImpretISR1.25%Resico','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-1.25','RCNRTE' => '-1.25','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IRT03','RCDESC' => 'ImpuestoCedular2%Resico','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-2','RCNRTE' => '-2','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IMP16','RCDESC' => 'IVATRASLADADO16%MMVO','RCEDTE' => '20130101','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '16','RCNRTE' => '16','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'IRT07','RCDESC' => 'ImpCedulararrendamiento2.5%','RCEDTE' => '20200101','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-2.5','RCNRTE' => '-2.5','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        ZRC::create(['RCID' => 'RC','RCRTCD' => 'RET02','RCDESC' => 'ImpretISR10%Arrendamiento','RCEDTE' => '20131231','RCCSET' => '','RCCTXR' => '','RCNTXR' => '','RCCTRA' => '','RCNTRA' => '','RCCTXP' => '','RCNTXP' => '','RCCTPA' => '','RCNTPA' => '','RCCRTE' => '-10','RCNRTE' => '-10','RCRNDM' => 'H','RCRNDP' => '1','RCTAXN' => '1','RCVATT' => '0','RCVATN' => '0','RCINPC' => '0','RCINFL' => '0',]);
        
    }
}
