<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AVM extends Model
{
    use HasFactory;
    // protected $dateFormat = 'Ymd H:i:s.v';
    // protected $connection = 'odbc-connection-lx834f02';
    protected $connection = 'odbc-connection-lx834f01';
    // protected $table = 'LX834F02.AVM';
    protected $table = 'LX834F01.AVM';
    public $timestamps = false; // Desactivar timestamps
    public $incrementing = false;
    protected $fillable = [
        'VNSTAT',
        'VMID',
        'VENDOR',
        'VNDNAM',
        'VNDAD1',
        'VNDAD2',
        'VSTATE',
        'VPOST',
        'VTERMS',
        'VTYPE',
        'VPAYTO',
        'VDTLPD',
        'VDAYCL',
        'V1099',
        'VPHONE',
        'VCMPNY',
        'VCURR',
        'VPAYTY',
        'V1TIME',
        'VCORPV',
        'VHOLD',
        'VHOLDT',
        'VPYTYR',
        'VDSCAV',
        'VDSCTK',
        'VDPURS',
        'VNNEXT',
        'VNGEN',
        'VNALPH',
        'VNUNAL',
        'VCON',
        'VCOUN',
        'V1099S',
        'VPAD1',
        'VPAD2',
        'VPSTE',
        'VPPST',
        'VPCON',
        'VPCOU',
        'VMFRM',
        'VMMAT',
        'VTAX',
        'VPPHN',
        'VMFSCD',
        'VMIDNM',
        'VTAXCD',
        'VMXCRT',
        'VMXDTE',
        'VMXMAX',
        'VMSRNO',
        'VMPREQ',
        'VMRELP',
        'VMVFAX',
        'VMPFAX',
        'VMRELM',
        'VMPART',
        'VMTRBR',
        'VMDATN',
        'VNDAD3',
        'VPAD3',
        'VMPDAT',
        'VMBANK',
        'VMAD5',
        'VMAD6',
        'VMLANG',
        'VMPAD4',
        'VMPAD5',
        'VMPAD6',
        'VMSHFM',
        'VMCCEX',
        'VMAYTD',
        'VMBNKC',
        'VMBRNO',
        'VMBNKA',
        'VMUF01',
        'VMUF02',
        'VMUF03',
        'VMUF04',
        'VMUF05',
        'VMUF06',
        'VMUF07',
        'VMUF08',
        'VMUF09',
        'VMUF10',
        'VM3WMF',
        'VMPKRA',
        'VMSFBF',
        'VMPPHZ',
        'VMFPHZ',
        'VMDIHZ',
        'VMDILT',
        'VMPPO',
        'VMAQPO',
        'VMCRAL',
        'VMCREC',
        'VMRGCD',
    ];

}
